services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend  # Keep for development
    environment:
      - NODE_ENV=staging
    depends_on:
      - frontend

  frontend:
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:  # Conditional volume mounting for development
      # Uncomment during development to reflect code changes:
      - ./:/app
    environment:
      - NODE_ENV=staging